flowchart TD
%% generated in 0.01s
    examples__integration_tests["examples.integration_tests<br/>11 funcs"]
    src__intract["src.intract<br/>193 funcs"]
    examples__integration_tests ==>|7| src__intract
